# -*- coding: utf-8 -*-
"""actividad-3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/jgilhe/f72bda21751e4d45777f8e4896200248/actividad-3.ipynb

# <font color=#BC89CC size= 7 face = times new roman >**Ejercicio 8.2**<font>

<font face = times new roman>Se requiere desarrollar un programa con interfaz gráfica de usuario que genere una ventana donde se solicite el ingreso de cinco notas obtenidas por un estudiante.

El programa debe calcular y mostrar en la parte inferior de la ventana los siguientes datos:


*   El promedio de notas ingresadas
*   La desviación estándar de las notas ingresadas
*   La mayor nota obtenida
*   La menor nota obtenida </font>
"""

import ipywidgets as widgets
from IPython.display import display, HTML
import statistics
from ipywidgets import ButtonStyle

class GradeCalculatorWidget:
    def __init__(self):
        # Input widgets
        self.grade_inputs = []
        for i in range(5):
            self.grade_inputs.append(widgets.FloatText(
                description=f'Nota {i+1}:',
                min=0.0,
                max=100.0,
                value=0.0,
                step=0.1,
                continuous_update=False
            ))

        # Output widgets
        self.output_avg = widgets.HTML(value="<p><b>Promedio:</b></p>")
        self.output_std_dev = widgets.HTML(value="<p><b>Desviación Estándar:</b></p>")
        self.output_max = widgets.HTML(value="<p><b>Mayor Nota:</b></p>")
        self.output_min = widgets.HTML(value="<p><b>Menor Nota:</b></p>")
        self.output_error = widgets.HTML(value="<p style='color:red;'></p>")

        # Define custom button style
        custom_button_style = ButtonStyle(button_color='#BC89CC')

        self.calculate_button = widgets.Button(
            description="Calcular",
            button_style='',
            style=custom_button_style # Apply the custom style here
        )
        self.calculate_button.on_click(self._calculate_grades)

        # Arrange widgets in containers
        self.grade_input_box = widgets.VBox(self.grade_inputs)
        self.result_output_box = widgets.VBox([
            self.output_avg,
            self.output_std_dev,
            self.output_max,
            self.output_min,
            self.output_error
        ])

        # Create the main display box
        self.main_box = widgets.VBox([
            self.grade_input_box,
            self.calculate_button,
            self.result_output_box
        ])

    def _calculate_grades(self, b):

        grades = []
        self.output_error.value = ""
        for i, input_widget in enumerate(self.grade_inputs):
            try:
                grade = input_widget.value
                if not (0 <= grade <= 100):
                    self.output_error.value = f"<p style='color:red;'>La Nota {i+1} debe estar entre 0 y 100.</p>"
                    return
                grades.append(grade)
            except ValueError:
                self.output_error.value = f"<p style='color:red;'>Por favor, ingrese un número válido para la Nota {i+1}.</p>"
                return

        if len(grades) == 5:
            # Calculate statistics
            average = sum(grades) / len(grades)
            std_dev = statistics.stdev(grades) if len(grades) > 1 else 0.0
            highest = max(grades)
            lowest = min(grades)

            # Update output widgets
            self.output_avg.value = f"<p><b>Promedio:</b> {average:.2f}</p>"
            self.output_std_dev.value = f"<p><b>Desviación Estándar:</b> {std_dev:.2f}</p>"
            self.output_max.value = f"<p><b>Mayor Nota:</b> {highest:.2f}</p>"
            self.output_min.value = f"<p><b>Menor Nota:</b> {lowest:.2f}</p>"
        else:
            self.output_error.value = "<p style='color:red;'>Por favor, ingrese las cinco notas.</p>"

    def display_widget(self):
        """Method to display the organized widget."""
        display(self.main_box)

grade_app = GradeCalculatorWidget()
grade_app.display_widget()

"""# <font color=#BC89CC size= 7 face = times new roman >**Ejercicio 8.3**<font>

<font  face = times new roman>Se requiere desarrollar un programa con interfaz gráfoca de usuario que permita calcular el volumen de la superficie de varias figuras geometricas. Las figuras geometricas son el cilindro, la esfera y la pirámide.

*   Para el cilindro se solicitara su radio y  altura (en centímetros)
*   Para la esfera, su radio (en centímetros)
*   Para la pirámide, su base, altura y apotema (en centímetros)

Una vez ingresados estos datos, el programa calcula el volumen y superficie de cada figura. Para desarrollar el programa se debe crear una jerarquía de clases para las diferentes figuras geométricas requeridas</font>

### Calculadora de Volumen y Superficie de Figuras Geométricas con `ipywidgets`

Este código implementa la lógica para calcular el volumen y el área superficial de cilindros, esferas y pirámides, y presenta una interfaz de usuario interactiva usando `ipywidgets` para funcionar directamente en Google Colab.
"""

import ipywidgets as widgets
from IPython.display import display, HTML
import math
from ipywidgets import ButtonStyle # Import ButtonStyle

class FiguraGeometrica:

    def calcular_volumen(self):
        raise NotImplementedError("El método calcular_volumen debe ser implementado por subclases.")

    def calcular_area(self):
        raise NotImplementedError("El método calcular_area debe ser implementado por subclases.")


# ================= CILINDRO =================

class Cilindro(FiguraGeometrica):

    def __init__(self, radio, altura):
        if radio <= 0 or altura <= 0:
            raise ValueError("El radio y la altura deben ser positivos.")
        self.radio = radio
        self.altura = altura

    def calcular_volumen(self):
        return math.pi * self.radio**2 * self.altura

    def calcular_area(self):
        return 2 * math.pi * self.radio * (self.radio + self.altura)


# ================= ESFERA =================

class Esfera(FiguraGeometrica):

    def __init__(self, radio):
        if radio <= 0:
            raise ValueError("El radio debe ser positivo.")
        self.radio = radio

    def calcular_volumen(self):
        return (4/3) * math.pi * self.radio**3

    def calcular_area(self):
        return 4 * math.pi * self.radio**2


# ================= PIRÁMIDE =================

class Piramide(FiguraGeometrica):

    def __init__(self, base, altura, apotema):
        if base <= 0 or altura <= 0 or apotema <= 0:
            raise ValueError("La base, altura y apotema deben ser positivos.")
        self.base = base
        self.altura = altura
        self.apotema = apotema

    def calcular_volumen(self):
        # Assuming a square base pyramid
        return (self.base**2 * self.altura) / 3

    def calcular_area(self):
        area_base = self.base**2
        # Lateral area of a square base pyramid with apotema
        area_lateral = 2 * self.base * self.apotema
        return area_base + area_lateral


# ================= INTERFAZ GRÁFICA con ipywidgets =================

class GeometricFigureCalculatorWidget:

    def __init__(self):
        # Dropdown for figure selection
        self.figure_selector = widgets.Dropdown(
            options=['Cilindro', 'Esfera', 'Pirámide'],
            value='Cilindro',
            description='Seleccione una figura:',
            disabled=False,
        )
        self.figure_selector.observe(self._update_inputs, names='value')

        self.radio_input = widgets.FloatText(description='Radio (cm):', min=0.0, value=1.0)
        self.altura_input = widgets.FloatText(description='Altura (cm):', min=0.0, value=1.0)
        self.base_input = widgets.FloatText(description='Base (cm):', min=0.0, value=1.0)
        self.apotema_input = widgets.FloatText(description='Apotema (cm):', min=0.0, value=1.0)

        self.inputs_output = widgets.VBox([])

        custom_button_style = ButtonStyle(button_color='#BC89CC')

        # Calculate button
        self.calculate_button = widgets.Button(
            description='Calcular',
            button_style='',
            style=custom_button_style,
            tooltip='Calcular volumen y área',
        )
        self.calculate_button.on_click(self._calculate)

        # Result display
        self.result_output = widgets.HTML(value="<p><b>Volumen:</b></p><p><b>Área Superficial:</b></p>")
        self.error_output = widgets.HTML(value="", layout=widgets.Layout(width='auto'))

        # Main layout
        self.main_box = widgets.VBox([
            self.figure_selector,
            self.inputs_output,
            self.calculate_button,
            self.result_output,
            self.error_output
        ])

        # Initial update of inputs
        self._update_inputs(None)

    def _update_inputs(self, change):
        selected_figure = self.figure_selector.value
        current_inputs = []

        if selected_figure == 'Cilindro':
            current_inputs = [self.radio_input, self.altura_input]
        elif selected_figure == 'Esfera':
            current_inputs = [self.radio_input]
        elif selected_figure == 'Pirámide':
            current_inputs = [self.base_input, self.altura_input, self.apotema_input]

        self.inputs_output.children = current_inputs
        self.error_output.value = ""
        self.result_output.value = "<p><b>Volumen:</b></p><p><b>Área Superficial:</b></p>"


    def _calculate(self, b):
        selected_figure = self.figure_selector.value
        figure_object = None
        self.error_output.value = ""
        self.result_output.value = "<p><b>Volumen:</b></p><p><b>Área Superficial:</b></p>"

        try:
            if selected_figure == 'Cilindro':
                radio = self.radio_input.value
                altura = self.altura_input.value
                figure_object = Cilindro(radio, altura)
            elif selected_figure == 'Esfera':
                radio = self.radio_input.value
                figure_object = Esfera(radio)
            elif selected_figure == 'Pirámide':
                base = self.base_input.value
                altura = self.altura_input.value
                apotema = self.apotema_input.value
                figure_object = Piramide(base, altura, apotema)

            if figure_object:
                volumen = figure_object.calcular_volumen()
                area = figure_object.calcular_area()
                self.result_output.value = (
                    f"<p><b>Volumen:</b> {volumen:.2f} cm³</p>"
                    f"<p><b>Área Superficial:</b> {area:.2f} cm²</p>"
                )
        except ValueError as e:
            self.error_output.value = f"<p style='color:red;'>Error: {e}</p>"
        except Exception as e:
            self.error_output.value = f"<p style='color:red;'>Error inesperado: {e}</p>"

    def display_widget(self):
        display(self.main_box)

geometric_app = GeometricFigureCalculatorWidget()
geometric_app.display_widget()